extends:
  - airbnb-base
  - plugin:prettier/recommended
env:
  es2021: true
  browser: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

overrides:
  - files: vite.config.js
    rules:
      import/no-extraneous-dependencies: off

  - files: src/index.js
    rules:
      no-param-reassign:
        - error
        - props: true
          ignorePropertyModificationsFor: [container]
