extends:
  - stylelint-config-sass-guidelines

rules:
  scss/dollar-variable-colon-space-after: always-single-line
  function-parentheses-space-inside: never-single-line
  selector-class-pattern: ^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$
  max-nesting-depth: 2
